# Generated by Django 5.1.15 on 2026-03-13 01:03

import django.db.models.deletion
from django.db import migrations, models


def seed_initial_portfolio(apps, schema_editor):
    SiteSettings = apps.get_model("resume", "SiteSettings")
    PortfolioSection = apps.get_model("resume", "PortfolioSection")
    SectionEntry = apps.get_model("resume", "SectionEntry")
    NavigationItem = apps.get_model("resume", "NavigationItem")

    SiteSettings.objects.create(
        pk=1,
        full_name="Junaid Hafeez",
        professional_title="Quality Automation Engineer",
        hero_intro=(
            "I build reliable web products with clean architecture, automation-first quality "
            "engineering, and scalable backend systems."
        ),
        about_text=(
            "Dedicated software and QA engineer with a strong background in Django, test "
            "automation, and process optimization. I focus on delivering maintainable code, "
            "stable releases, and measurable business impact."
        ),
        email="junaidhafeez.cs@gmail.com",
        phone="+92 306 9287947",
        address="402B City Tower, Gulberg, Lahore",
        linkedin_url="https://www.linkedin.com/in/junadhafeezcs",
        github_url="https://github.com/junaidhafeez",
        website_url="https://www.appifytech.com",
        profile_image="images/junaid.jpg",
        footer_text="Copyright 2026. All rights reserved.",
        resume_filename="Junaid_Hafeez_Resume",
    )

    projects = PortfolioSection.objects.create(
        title="Projects",
        slug="projects",
        nav_title="Projects",
        headline="Featured Projects",
        description="Selected work covering product development, automation, and enterprise workflows.",
        icon_class="fas fa-diagram-project",
        order=1,
        is_visible=True,
        show_on_resume=True,
    )
    experience = PortfolioSection.objects.create(
        title="Experience",
        slug="experience",
        nav_title="Experience",
        headline="Professional Experience",
        description="Hands-on roles in QA automation, software quality, and engineering execution.",
        icon_class="fas fa-briefcase",
        order=2,
        is_visible=True,
        show_on_resume=True,
    )
    education = PortfolioSection.objects.create(
        title="Education",
        slug="education",
        nav_title="Education",
        headline="Education",
        description="Academic qualifications and ongoing learning track.",
        icon_class="fas fa-graduation-cap",
        order=3,
        is_visible=True,
        show_on_resume=True,
    )
    certifications = PortfolioSection.objects.create(
        title="Certifications",
        slug="certifications",
        nav_title="Certifications",
        headline="Certifications",
        description="Professional certifications in QA and automation.",
        icon_class="fas fa-certificate",
        order=4,
        is_visible=True,
        show_on_resume=True,
    )

    SectionEntry.objects.bulk_create(
        [
            SectionEntry(
                section=projects,
                title="Inventory Management System",
                subtitle="Django Application",
                date_range="2024",
                description="End-to-end inventory operations platform with role-based controls and reporting.",
                bullet_points=(
                    "Built modular inventory, alerts, and reporting workflows\n"
                    "Improved tracking accuracy with real-time stock updates"
                ),
                tags="Python, Django, PostgreSQL, Bootstrap",
                order=1,
            ),
            SectionEntry(
                section=projects,
                title="Pharmacy Management System",
                subtitle="Business Automation Platform",
                date_range="2023",
                description="Operational system for inventory, prescriptions, and point-of-sale activities.",
                bullet_points=(
                    "Delivered expiry alerts and billing automation\n"
                    "Improved medicine handling through better categorization"
                ),
                tags="Python, Django, MySQL, JavaScript",
                order=2,
            ),
            SectionEntry(
                section=experience,
                title="Quality Automation Engineer",
                subtitle="AppifyTech",
                date_range="2022 - Present",
                description="Driving test automation strategy and release quality for web products.",
                bullet_points=(
                    "Designed reusable automation suites for regression coverage\n"
                    "Partnered with engineering to prevent recurring production defects"
                ),
                tags="QA, Selenium, Cypress, CI/CD",
                order=1,
            ),
            SectionEntry(
                section=experience,
                title="Automation Quality Engineer",
                subtitle="IT Cures",
                date_range="2021 - 2022",
                description="Created automation frameworks and introduced quality metrics for delivery teams.",
                bullet_points=(
                    "Reduced repetitive manual testing effort\n"
                    "Improved test reliability and pipeline signal quality"
                ),
                tags="Automation, Quality Engineering, Python",
                order=2,
            ),
            SectionEntry(
                section=education,
                title="Master's in Education",
                subtitle="University of Education",
                date_range="2023",
                description="Advanced work in pedagogy and educational methodologies.",
                order=1,
            ),
            SectionEntry(
                section=education,
                title="BS Computer Science",
                subtitle="Islamia University Bahawalpur",
                date_range="2017",
                description="Core computer science and software engineering foundation.",
                order=2,
            ),
            SectionEntry(
                section=certifications,
                title="ISTQB Certified",
                subtitle="Quality Assurance Engineer",
                date_range="2022",
                description="Professional credential for software testing principles and quality standards.",
                order=1,
            ),
        ]
    )

    NavigationItem.objects.bulk_create(
        [
            NavigationItem(label="Top", custom_url="/#top", order=1, is_active=True),
            NavigationItem(label="About", custom_url="/#about", order=2, is_active=True),
            NavigationItem(label="Projects", section=projects, order=3, is_active=True),
            NavigationItem(label="Experience", section=experience, order=4, is_active=True),
            NavigationItem(label="Education", section=education, order=5, is_active=True),
            NavigationItem(label="Contact", custom_url="/#contact", order=6, is_active=True),
        ]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('nav_title', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, default='fas fa-star', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('show_on_resume', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Your Name', max_length=120)),
                ('professional_title', models.CharField(default='Software Engineer', max_length=180)),
                ('hero_intro', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('profile_image', models.CharField(blank=True, default='images/junaid.jpg', help_text='Path relative to static folder, e.g. images/profile.jpg', max_length=255)),
                ('footer_text', models.CharField(blank=True, default='All rights reserved.', max_length=255)),
                ('resume_filename', models.CharField(default='resume', max_length=120)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('custom_url', models.CharField(blank=True, help_text='Use for internal or external links when section is not selected.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, help_text='If selected, URL will automatically use #section-slug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='resume.portfoliosection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('date_range', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('bullet_points', models.TextField(blank=True, help_text='Write one bullet per line for best formatting.')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags, e.g. Django, Python, AWS', max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resume.portfoliosection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_initial_portfolio, migrations.RunPython.noop),
    ]
