# Generated by Django 5.1.15 on 2026-03-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload profile image from admin panel.', null=True, upload_to='profile/'),
        ),
    ]
