# Generated by Django 5.1.15 on 2026-03-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_sitesettings_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_label',
            field=models.CharField(default='Address', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_label',
            field=models.CharField(default='Email', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_subject_prefix',
            field=models.CharField(default='Portfolio Contact Form', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_failure_message',
            field=models.CharField(default='There was an error sending your message. Please try again later.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title',
            field=models.CharField(default='Send a Message', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info_title',
            field=models.CharField(default='Contact Information', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_linkedin_label',
            field=models.CharField(default='LinkedIn', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_message_label',
            field=models.CharField(default='Message', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_name_label',
            field=models.CharField(default='Name', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_label',
            field=models.CharField(default='Phone', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_required_fields_error',
            field=models.CharField(default='All fields are required.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_saved_only_message',
            field=models.CharField(default='Message saved successfully. Email delivery is currently unavailable.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_subtitle',
            field=models.CharField(default='Feel free to reach out through the details below or the message form.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title',
            field=models.CharField(default='Get in Touch', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_send_button_text',
            field=models.CharField(default='Send Message', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subject_label',
            field=models.CharField(default='Subject', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_success_message',
            field=models.CharField(default='Your message has been sent successfully!', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_website_label',
            field=models.CharField(default='Website', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title',
            field=models.CharField(default='Contact Information', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_links_title',
            field=models.CharField(default='Quick Links', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_title',
            field=models.CharField(default='Connect With Me', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_title',
            field=models.CharField(default='About Me', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_download_resume_button_text',
            field=models.CharField(default='Download Resume PDF', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_no_entries_text',
            field=models.CharField(default='No entries added yet. Add content from admin panel.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_open_link_text',
            field=models.CharField(default='Open Link', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_view_resume_button_text',
            field=models.CharField(default='View Resume', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_welcome_title',
            field=models.CharField(default='Welcome to my professional portfolio', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pdf_profile_summary_title',
            field=models.CharField(default='PROFILE SUMMARY', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pdf_technologies_label',
            field=models.CharField(default='Technologies', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_download_button_text',
            field=models.CharField(default='Download Resume (PDF)', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_no_sections_text',
            field=models.CharField(default='No resume sections are configured yet. Add sections from admin panel.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_page_subtitle',
            field=models.CharField(default='A comprehensive overview of my professional journey, skills, and achievements.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_page_title',
            field=models.CharField(default='Professional Resume', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_profile_title',
            field=models.CharField(default='Profile', max_length=120),
        ),
    ]
