# Generated by Django 5.1.15 on 2026-03-13 02:19

from django.db import migrations, models


def migrate_resume_labels(apps, schema_editor):
    SiteSettings = apps.get_model("resume", "SiteSettings")
    for settings in SiteSettings.objects.all():
        previous_label = getattr(settings, "home_view_resume_button_text", "") or ""
        if previous_label.strip():
            settings.navbar_resume_button_text = previous_label
        if (settings.resume_profile_title or "").strip().lower() == "profile":
            settings.resume_profile_title = "Professional Summary"
        settings.save(update_fields=["navbar_resume_button_text", "resume_profile_title"])


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_sitesettings_contact_address_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_resume_button_text',
            field=models.CharField(default='View Resume', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_print_button_text',
            field=models.CharField(default='Print Resume', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='resume_profile_title',
            field=models.CharField(default='Professional Summary', max_length=120),
        ),
        migrations.RunPython(migrate_resume_labels, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='home_download_resume_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='home_view_resume_button_text',
        ),
    ]
