# Generated by Django 5.1.15 on 2026-03-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_sitesettings_home_download_resume_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='resume_download_button_text',
            field=models.CharField(default='Download Resume', max_length=120),
        ),
    ]
