# Generated by Django 5.1.15 on 2026-03-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_sitesettings_resume_download_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_resume_button_text',
        ),
    ]
