# Generated by Django 5.1.15 on 2026-03-13 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_sitesettings_navbar_resume_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Main introductory body text.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/covers/')),
                ('author_name', models.CharField(default='Admin', max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_back_to_blogs_text',
            field=models.CharField(default='Back to Blogs', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_no_posts_text',
            field=models.CharField(default='No blogs published yet.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle',
            field=models.CharField(default='Thoughts, updates, and practical notes from daily work.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title',
            field=models.CharField(default='Latest Blogs', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_read_more_text',
            field=models.CharField(default='Read More', max_length=80),
        ),
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=12)),
                ('heading', models.CharField(blank=True, max_length=180)),
                ('text_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/blocks/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='blogs/blocks/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube/Vimeo/MP4).')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='resume.blogpost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
