# Generated by Django 5.1.15 on 2026-03-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_blogpost_sitesettings_blog_back_to_blogs_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_categories_title',
            field=models.CharField(default='Categories', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_category_label_text',
            field=models.CharField(default='Category', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comment_email_label',
            field=models.CharField(default='Email', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comment_message_label',
            field=models.CharField(default='Message', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comment_name_label',
            field=models.CharField(default='Name', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comment_pending_text',
            field=models.CharField(default='Your comment was submitted and will appear after approval.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comment_submit_text',
            field=models.CharField(default='Post Comment', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_comments_title',
            field=models.CharField(default='Comments', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_filter_all_text',
            field=models.CharField(default='All', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_no_comments_text',
            field=models.CharField(default='No comments yet.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_search_button_text',
            field=models.CharField(default='Search', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_search_placeholder',
            field=models.CharField(default='Search blogs...', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_tags_title',
            field=models.CharField(default='Tags', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='resume.blogcategory'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resume.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='resume.blogtag'),
        ),
    ]
