# Generated by Django 5.1.15 on 2026-03-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_blogcategory_blogtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosection',
            name='show_on_resume',
            field=models.BooleanField(default=True, help_text='Enable to include this section on Resume preview and PDF.', verbose_name='Show on CV/Resume'),
        ),
    ]
