# Generated by Django 5.1.15 on 2026-03-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_portfoliosection_show_on_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='downloads/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='downloads/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-uploaded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_back_text',
            field=models.CharField(default='Back to Downloads', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_download_text',
            field=models.CharField(default='Download', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_no_items_text',
            field=models.CharField(default='No files uploaded yet.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_open_text',
            field=models.CharField(default='Open', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_page_subtitle',
            field=models.CharField(default='Access useful files, resources, and documents.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_page_title',
            field=models.CharField(default='Downloads', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_preview_unavailable_text',
            field=models.CharField(default='Preview is not available for this file type. Use download button.', max_length=180),
        ),
    ]
