# Generated by Django 5.1.15 on 2026-03-13 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_downloaditem_sitesettings_downloads_back_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_bulk_download_text',
            field=models.CharField(default='Download Selected (ZIP)', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_categories_title',
            field=models.CharField(default='Categories', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_filter_all_text',
            field=models.CharField(default='All', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_office_preview_note',
            field=models.CharField(default='Office preview may require internet/public URL access.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='downloads_select_item_text',
            field=models.CharField(default='Select', max_length=80),
        ),
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resume.downloadcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='resume.downloadcategory'),
        ),
    ]
