# Generated by Django 5.1.15 on 2026-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_sitesettings_downloads_bulk_download_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for this section only.', null=True, upload_to='backgrounds/sections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_theme',
            field=models.CharField(choices=[('ocean', 'Ocean Blue'), ('emerald', 'Emerald Pro'), ('sunset', 'Sunset Glow'), ('mono', 'Monochrome Luxe')], default='ocean', help_text='Select a complete color theme for the website.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_background_image',
            field=models.ImageField(blank=True, help_text='Optional full-website background image with subtle reflection overlay.', null=True, upload_to='backgrounds/site/'),
        ),
    ]
