# Generated by Django 5.1.15 on 2026-03-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_portfoliosection_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='color_theme',
            field=models.CharField(choices=[('ocean', 'Ocean Blue'), ('emerald', 'Emerald Pro'), ('sunset', 'Sunset Glow'), ('mono', 'Monochrome Luxe'), ('royal', 'Royal Purple'), ('crimson', 'Crimson Night'), ('aurora', 'Aurora Mint')], default='ocean', help_text='Select a complete color theme for the website.', max_length=20),
        ),
    ]
