# Generated by Django 5.0.6 on 2026-03-24 22:35

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_sitesettings_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='body_text_color',
            field=models.CharField(blank=True, help_text='Project cards: titles, body, bullets (not tag pills).', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='description_color',
            field=models.CharField(blank=True, help_text='Section description line.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='title_color',
            field=models.CharField(blank=True, help_text='Section headline (hex). Blank = theme default.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_color',
            field=models.CharField(blank=True, help_text='About section: body paragraph.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_subtitle_color',
            field=models.CharField(blank=True, help_text='About section: subtitle.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_color',
            field=models.CharField(blank=True, help_text='About section: main heading.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_body_color',
            field=models.CharField(blank=True, help_text='Contact: card text, labels, and form labels.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_subtitle_color',
            field=models.CharField(blank=True, help_text='Contact: subtitle under title.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title_color',
            field=models.CharField(blank=True, help_text='Contact: main section title.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_intro_color',
            field=models.CharField(blank=True, help_text='Hero: intro paragraph under welcome.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_name_color',
            field=models.CharField(blank=True, help_text='Hero: your name (hex, e.g. #e8eef7). Blank = theme default.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_color',
            field=models.CharField(blank=True, help_text='Hero: professional title line.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_welcome_title_color',
            field=models.CharField(blank=True, help_text='Hero: welcome heading.', max_length=7, validators=[resume.models.validate_optional_hex_color]),
        ),
    ]
